"""create automation rules

Revision ID: 02f445557e18
Revises: 6f47d2fe32a6
Create Date: 2026-10-01 14:57:50.830131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02f445557e18'
down_revision: Union[str, Sequence[str], None] = '6f47d2fe32a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger_type', sa.String(length=100), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('action_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_rules_created_by'), 'automation_rules', ['created_by'], unique=False)
    op.create_index(op.f('ix_automation_rules_id'), 'automation_rules', ['id'], unique=False)
    op.create_index(op.f('ix_automation_rules_is_active'), 'automation_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_automation_rules_trigger_type'), 'automation_rules', ['trigger_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_automation_rules_trigger_type'), table_name='automation_rules')
    op.drop_index(op.f('ix_automation_rules_is_active'), table_name='automation_rules')
    op.drop_index(op.f('ix_automation_rules_id'), table_name='automation_rules')
    op.drop_index(op.f('ix_automation_rules_created_by'), table_name='automation_rules')
    op.drop_table('automation_rules')
    # ### end Alembic commands ###
