"""add opportunity crm fields

Revision ID: 132ec5fb2ac3
Revises: af97efd9a7c4
Create Date: 2026-08-18 17:08:26.883693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '132ec5fb2ac3'
down_revision: Union[str, Sequence[str], None] = 'af97efd9a7c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('priority', sa.String(length=20), server_default='medium', nullable=False))
    op.add_column('opportunities', sa.Column('probability', sa.Integer(), server_default='20', nullable=False))
    op.add_column('opportunities', sa.Column('expected_close_date', sa.Date(), nullable=True))
    op.add_column('opportunities', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('opportunities', sa.Column('assigned_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_opportunities_assigned_user_id'), 'opportunities', ['assigned_user_id'], unique=False)
    op.create_foreign_key(None, 'opportunities', 'users', ['assigned_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'opportunities', type_='foreignkey')
    op.drop_index(op.f('ix_opportunities_assigned_user_id'), table_name='opportunities')
    op.drop_column('opportunities', 'assigned_user_id')
    op.drop_column('opportunities', 'notes')
    op.drop_column('opportunities', 'expected_close_date')
    op.drop_column('opportunities', 'probability')
    op.drop_column('opportunities', 'priority')
    # ### end Alembic commands ###
