"""add structured stage data to opportunity events

Revision ID: 63492320c1bd
Revises: 7f0c34b27f52
Create Date: 2026-08-20 15:36:15.940553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63492320c1bd'
down_revision: Union[str, Sequence[str], None] = '7f0c34b27f52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity_events', sa.Column('old_stage', sa.String(length=50), nullable=True))
    op.add_column('opportunity_events', sa.Column('new_stage', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_opportunity_events_new_stage'), 'opportunity_events', ['new_stage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunity_events_new_stage'), table_name='opportunity_events')
    op.drop_column('opportunity_events', 'new_stage')
    op.drop_column('opportunity_events', 'old_stage')
    # ### end Alembic commands ###
