"""create opportunity events

Revision ID: 7f0c34b27f52
Revises: eb51c9513543
Create Date: 2026-08-20 11:16:56.399665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f0c34b27f52'
down_revision: Union[str, Sequence[str], None] = 'eb51c9513543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_events_event_type'), 'opportunity_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_opportunity_events_id'), 'opportunity_events', ['id'], unique=False)
    op.create_index(op.f('ix_opportunity_events_opportunity_id'), 'opportunity_events', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_opportunity_events_user_id'), 'opportunity_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunity_events_user_id'), table_name='opportunity_events')
    op.drop_index(op.f('ix_opportunity_events_opportunity_id'), table_name='opportunity_events')
    op.drop_index(op.f('ix_opportunity_events_id'), table_name='opportunity_events')
    op.drop_index(op.f('ix_opportunity_events_event_type'), table_name='opportunity_events')
    op.drop_table('opportunity_events')
    # ### end Alembic commands ###
