"""add opportunity id to activities

Revision ID: eb51c9513543
Revises: 132ec5fb2ac3
Create Date: 2026-08-19 21:04:29.932328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb51c9513543'
down_revision: Union[str, Sequence[str], None] = '132ec5fb2ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('opportunity_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_activities_opportunity_id'), 'activities', ['opportunity_id'], unique=False)
    op.create_foreign_key(
        'fk_activities_opportunity_id_opportunities',
        'activities',
        'opportunities',
        ['opportunity_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_activities_opportunity_id_opportunities',
        'activities',
        type_='foreignkey',
    )
    op.drop_index(op.f('ix_activities_opportunity_id'), table_name='activities')
    op.drop_column('activities', 'opportunity_id')
    # ### end Alembic commands ###
